version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.88.0
    container_name: n8n_service
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=production
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - TZ=Asia/Shanghai
      # Add your sensitive environment variables here
      # - MCP_OPENAI_API_KEY=your-key
      # - MCP_SERPER_API_KEY=your-key
      # - MCP_WEATHER_API_KEY=your-key
      # - MCP_BRAVE_API_KEY=your-key
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    name: n8n-docker_n8n_data 